export const GAME_TITLE = "FINAL FELINE";

export const ENTITY_MOVING_DISTANCE = 256;
export const ENTITY_WALKING_VELOCITY = 2;
export const ENTITY_SCALE = 4;
export const ENTITY_VITAL_BAR_WIDTH = 17;
export const ENTITY_VITAL_BAR_HEIGHT = 5;
export const ENTITY_ATB_BAR_HEIGHT = 4;
export const ENTITY_FINALE_BAR_WIDTH = 3;
export const ENTITY_FINALE_BAR_HEIGHT = 19;
export const ENTITY_VITAL_BAR_X_OFFSET = 48;
export const ENTITY_VITAL_BAR_Y_OFFSET = 19;
export const ENTITY_VITAL_BAR_Y_DISTANCE = 6;
export const ENTITY_READY_FLASH_SPEED = 0.05;
export const ENTITY_HUE_TWEAK_PARAMETER = 40;

export const PUB_POPULATION_MINIMUM = 3;
export const PUB_POPULATION_MAXIMUM = 8;

export const MESSAGE_BOX_PADDING = 4;
export const SCREEN_MESSAGE_BOX_MARGIN = 64;
export const MESSAGE_BOX_PROGRESSIVE_DISPLAY_RATE = 3; // A letter every x frames

export const STANDARD_ANIMATION_SPEED = 0.1;
export const SLOWED_ANIMATION_SPEED = STANDARD_ANIMATION_SPEED / 2;
export const FASTER_ANIMATION_SPEED = STANDARD_ANIMATION_SPEED * 2;

export const AFFLICTION_SCALE = 2;

export const IMPACT_SCALE = 4;
export const IMPACT_ANIMATION_SPEED = STANDARD_ANIMATION_SPEED;

export const ITEM_SCALE = 3;

export const CAST_SHADOW_WIDTH_UP = 25;
export const CAST_SHADOW_WIDTH_DOWN = 60;

export const BATTLE_TOP_MARGIN = 256;
export const BATTLE_CHARACTER_SEPARATION = 64;

export const FAPPLE_HP_RECOVERY = [10, 30];
export const RICH_BITCH_JUICE_MP_RECOVERY = [8, 24];

export const AI_TURNS_BEFORE_FIRST_BUFF = 3;
export const AI_DEFAULT_BUFF_RATE_IN_TURNS = 5;
export const AI_ESCAPE_SUCCESS_RATE = 20;
export const AI_DEFAULT_SKILL_CAST_RATE = 30;

export const SCREEN_FADE_TIME_IN_MS = 1500;