export const GAME_TITLE = "FINAL FELINE";

export const ENTITY_MOVING_DISTANCE = 256;
export const ENTITY_WALKING_VELOCITY = 2;
export const ENTITY_SCALE = 5;

export const PUB_POPULATION_MINIMUM = 3;
export const PUB_POPULATION_MAXIMUM = 8;

export const MESSAGE_BOX_PADDING = 4;
export const SCREEN_MESSAGE_BOX_MARGIN = 64;
export const MESSAGE_BOX_PROGRESSIVE_DISPLAY_RATE = 3; // A letter every x frames

export const STANDARD_ANIMATION_SPEED = 0.1;
export const SLOWED_ANIMATION_SPEED = STANDARD_ANIMATION_SPEED/2;
export const FASTER_ANIMATION_SPEED = STANDARD_ANIMATION_SPEED*2;

export const AFFLICTION_SCALE = 2;

export const CAST_SHADOW_WIDTH_UP = 25;
export const CAST_SHADOW_WIDTH_DOWN = 60;